SesionesBundle\Entity\Contacto:
    type: entity
    table: contacto
    id:
        idContacto:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_contacto
            generator:
                strategy: SEQUENCE
    fields:
        idUsuario:
            type: integer
            nullable: false
            unsigned: false
            column: id_usuario
        nombre:
            type: string
            nullable: false
            length: null
            fixed: false
            default: '255'
        apellido:
            type: string
            nullable: true
            length: 255
            fixed: false
        fechaNacimiento:
            type: date
            nullable: true
            column: fecha_nacimiento
        telefono:
            type: string
            nullable: true
            length: 255
            fixed: false
        correo:
            type: string
            nullable: true
            length: null
            fixed: false
        direccion:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
