SesionesBundle\Entity\Usuario:
    type: entity
    table: usuario
    uniqueConstraints:
        usuario_correo_uindex:
            columns:
                - correo
    id:
        idUsuario:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: id_usuario
            generator:
                strategy: SEQUENCE
    fields:
        nombre:
            type: string
            nullable: true
            length: 255
            fixed: false
        correo:
            type: string
            nullable: false
            length: 255
            fixed: false
        clave:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
